{
 "title": "Pizza Service Dev 8",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{source=\"jwt-pizza-service\", method=\"all\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "{source=\"jwt-pizza-service\", method=\"get\"}",
     "legendFormat": "get"
    },
    {
     "expr": "{source=\"jwt-pizza-service\", method=\"put\"}",
     "legendFormat": "put"
    },
    {
     "expr": "{source=\"jwt-pizza-service\", method=\"post\"}",
     "legendFormat": "post"
    },
    {
     "expr": "{source=\"jwt-pizza-service\", method=\"delete\"}",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "{source=\"jwt-pizza-service\", type=\"failed\"}",
     "legendFormat": "failed authentication"
    },
    {
     "expr": "{source=\"jwt-pizza-service\", type=\"successful\"}",
     "legendFormat": "success authentication"
    }
   ]
  },
  {
   "title": "Avg. Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=\"service\", __proxy_source__=\"influx\", metric=\"average_latency\", source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "purchase{source=\"jwt-pizza-service\", metric=\"average_purchase_latency\"}",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "purchase{source=\"jwt-pizza-service\", metric=\"total_quantity\"}",
     "legendFormat": "Total Purchases"
    },
    {
     "expr": "purchase{source=\"jwt-pizza-service-dev\", metric=\"failed_purchases\"}",
     "legendFormat": "Failed Purchases"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purchase{source=\"jwt-pizza-service\", metric=\"total_revenue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "active_users_count{__proxy_source__=\"influx\", source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg({source=\"jwt-pizza-service\", type=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{source=\"jwt-pizza-service\", type=\"memory\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}